services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - ENV_FILE=.env.local
    image: myapp
    env_file:
      - .env.local
    environment:
      - REDIS_HOST=redis:6379
      - MONGODB_URL=mongodb://mongodb:27017/myapp?replicaSet=rs0&authSource=admin&directConnection=true
      - AWS_MINIO_ENDPOINT=http://localhost:9000
    ports:
      - '3333:3333'
    command: /bin/sh -c "./docker/be-entrypoint.sh && yarn backend"
    healthcheck:
      test: curl --fail http://localhost:3333 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      - mongodb
      - redis
    networks:
      - myapp-network

  frontend:
    container_name: frontend
    image: myapp
    env_file:
      - .env.local
    ports:
      - '3000:3000'
    command: /bin/sh -c "./docker/fe-entrypoint.sh && yarn prod:fe"
    depends_on:
      - backend
    networks:
      - myapp-network

volumes:
  mongodb-data:
  minio-data:
  mongodb-config:

networks:
  myapp-network:
    driver: bridge
