[build]
  command = "npm run build:fe"
  publish = "./dist/packages/ui-app/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[template.environment]
  NEXT_PUBLIC_APP_NAME = "NEXT_PUBLIC_APP_NAME"
  NEXT_PUBLIC_BE_GATEWAY = "NEXT_PUBLIC_BE_GATEWAY"

[context.production]
  environment = { }

[context.deploy-preview]
  environment = { }
